/**
 * dsh-open-in-app — Node half.
 *
 * The pack's own launcher for the "Open In..." split button's FILE MANAGERS.
 * The shipped `@deepseek-ai/dsh-host-open-in-app` opens a directory through the
 * OS shell's open verb (`Invoke-Item` via `powershell.exe` on Windows,
 * `open` on macOS, `xdg-open` on Linux). That detour reports success as soon as
 * the shell helper exits, so a host where the hand-off goes nowhere - a
 * non-default directory handler, a PowerShell that cannot reach the interactive
 * desktop, a stripped PATH - shows nothing and says nothing.
 *
 * This row opens the OS's own file browser DIRECTLY instead, per platform:
 *
 *   win32   %SystemRoot%\explorer.exe <dir>      (Windows Explorer, always)
 *   darwin  open <dir>                            (Finder / the folder's app)
 *   linux   xdg-open <dir>
 *   WSL     wslpath -w <dir> then explorer.exe     (the Windows desktop)
 *
 * The cheap JSON contract is the only thing the browser half shares with the
 * shipped routes; the catalog, the icons, and every non-file-manager launch
 * still come from the shipped host row, which stays mounted. Only the client
 * bundle is forked (packages/dsh-open-in-app/lib/client.js, generated by
 * scripts/sync-vendored.ps1) so the "File Explorer" / "Finder" / "Files" menu
 * entries post here while every other entry keeps using the shipped route.
 *
 * Security is the shipped row's story and this route repeats it: the browser
 * authentication and the Host/Origin fence are enforced by the `connection`
 * service the route registers through, and the body is validated at the wire -
 * a JSON content type, a known file-manager id, and an absolute path naming an
 * existing directory. Nothing else is accepted, and never a command string:
 * the launcher spawns an argv array.
 */
import { spawn, execFile } from 'node:child_process'
import { stat } from 'node:fs/promises'
import { release } from 'node:os'
import { isAbsolute, join } from 'node:path'

export const name = 'dsh-open-in-app'

/** The route carrier whose authentication and origin fence every request passes. */
export const inject = ['connection']

/** Keep in sync with the client's hard-coded route constant. */
const OPEN_ROUTE = '/api/dsh-open-in-app/open'

/** The catalog ids whose launch is a file manager rather than an editor/terminal. */
const FILE_MANAGER_APPS = new Set(['finder', 'explorer', 'filemanager'])

/** How long an early failure is watched for before a launch counts as started. */
const WATCH_MS = 1200

/** Windows Explorer exits 1 when it hands the request to the running process. */
const EXPLORER_OK_CODES = new Set([0, 1])

/** Respond with a JSON body and a status code. */
function json(status, body) {
  return new Response(JSON.stringify(body), {
    status,
    headers: {
      'content-type': 'application/json; charset=utf-8',
      'cache-control': 'no-store',
    },
  })
}

function fail(status, code, message) {
  return json(status, { ok: false, error: { code, message } })
}

/** Whether this Linux host is really a Windows desktop reached through WSL. */
function isWsl(env) {
  const source = env || process.env
  if (typeof source.WSL_DISTRO_NAME === 'string' && source.WSL_DISTRO_NAME !== '') return true
  if (typeof source.WSL_INTEROP === 'string' && source.WSL_INTEROP !== '') return true
  try {
    return release().toLowerCase().includes('microsoft')
  } catch (e) {
    return false
  }
}

/** The absolute path of the Windows shell's file browser. */
function explorerPath(env) {
  const root = (env && (env.SystemRoot || env.windir)) || 'C:\\Windows'
  return join(root, 'explorer.exe')
}

/** `wslpath -w <path>`: the Windows spelling of one Linux path. */
function wslWindowsPath(path) {
  return new Promise((resolve, reject) => {
    execFile('wslpath', ['-w', path], { encoding: 'utf8', windowsHide: true }, (error, stdout) => {
      if (error) {
        reject(new Error('wslpath could not translate the path: ' + error.message))
        return
      }
      const translated = String(stdout).replace(/[\r\n]+$/, '')
      if (translated === '') {
        reject(new Error('wslpath returned no Windows path'))
        return
      }
      resolve(translated)
    })
  })
}

/**
 * Spawn one launcher detached and classify how the attempt ended: an early
 * `error` (a missing executable) or a nonzero exit inside the watch window is a
 * failure, while a child still running when the window closes counts as
 * launched and keeps running.
 *
 * @param command - executable path or PATH name.
 * @param args - argv (never a shell string).
 * @param accepted - exit codes that mean "handed over", not "failed".
 * @returns `{ ok: true }` or `{ ok: false, message }`.
 */
function launchDetached(command, args, accepted) {
  return new Promise((resolve) => {
    let child
    try {
      child = spawn(command, args, { detached: true, stdio: 'ignore', windowsHide: false })
    } catch (error) {
      resolve({ ok: false, message: error && error.message ? error.message : String(error) })
      return
    }
    let settled = false
    const finish = (outcome) => {
      if (settled) return
      settled = true
      clearTimeout(watch)
      try {
        child.unref()
      } catch (e) {}
      resolve(outcome)
    }
    const watch = setTimeout(() => finish({ ok: true }), WATCH_MS)
    child.on('error', (error) => {
      finish({ ok: false, message: error && error.message ? error.message : String(error) })
    })
    child.on('exit', (code) => {
      if (accepted.has(code)) finish({ ok: true })
      else finish({ ok: false, message: 'the launcher exited with code ' + String(code) })
    })
  })
}

/**
 * Open one directory in this platform's file browser.
 * @param path - absolute directory path (already validated).
 * @returns `{ ok: true }` or `{ ok: false, message }`.
 */
async function openInFileBrowser(path) {
  const platform = process.platform
  if (platform === 'win32') {
    return launchDetached(explorerPath(process.env), [path], EXPLORER_OK_CODES)
  }
  if (platform === 'darwin') {
    return launchDetached('open', [path], new Set([0]))
  }
  if (platform === 'linux') {
    if (isWsl(process.env)) {
      try {
        const translated = await wslWindowsPath(path)
        return launchDetached(explorerPath(process.env), [translated], EXPLORER_OK_CODES)
      } catch (error) {
        return { ok: false, message: error && error.message ? error.message : String(error) }
      }
    }
    return launchDetached('xdg-open', [path], new Set([0]))
  }
  return { ok: false, message: 'no file browser is known for ' + platform }
}

/** POST /api/dsh-open-in-app/open — open one workspace directory in the OS file browser. */
async function handleOpen(request) {
  let payload
  try {
    payload = await request.json()
  } catch (err) {
    return fail(400, 'BAD_REQUEST', 'Expected a JSON body.')
  }
  const app = typeof payload.app === 'string' ? payload.app : ''
  const path = typeof payload.path === 'string' ? payload.path : ''
  if (!FILE_MANAGER_APPS.has(app)) {
    return fail(400, 'BAD_REQUEST', 'Unsupported file-manager application: ' + (app || '(none)'))
  }
  if (path === '' || !isAbsolute(path)) {
    return fail(400, 'BAD_REQUEST', 'The path must be an absolute directory path.')
  }
  let isDirectory = false
  try {
    isDirectory = (await stat(path)).isDirectory()
  } catch (err) {
    isDirectory = false
  }
  if (!isDirectory) {
    return fail(404, 'NOT_FOUND', 'The directory does not exist: ' + path)
  }
  const outcome = await openInFileBrowser(path)
  if (outcome.ok !== true) {
    return fail(502, 'LAUNCH_FAILED', 'Could not open ' + path + ' in the system file browser: ' + outcome.message)
  }
  return json(200, { ok: true })
}

/**
 * Activate the plugin row: register the launcher route.
 * @param ctx - cordis context (inject: connection).
 */
export function apply(ctx) {
  const connection = ctx.get ? ctx.get('connection') : undefined
  if (!connection || !connection.fetch || typeof connection.fetch.register !== 'function') {
    ctx.logger?.warn?.('[dsh-open-in-app] connection service unavailable - file browser route not registered')
    return
  }
  ctx.effect(() => {
    const off = connection.fetch.register({
      path: OPEN_ROUTE,
      methods: ['POST'],
      // REQUIRED: Connection's HTTP bridge picks the streaming branch for a
      // route that leaves this undefined (the same reason dsh-editor sets it).
      requestBody: 'buffered',
      fetch: handleOpen,
    })
    ctx.logger?.debug?.('[dsh-open-in-app] file browser route active (' + OPEN_ROUTE + ')')
    return () => {
      try {
        off()
      } catch (e) {}
    }
  }, 'dsh-open-in-app: file browser route')
}
